export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGS_ERROR = "FETCH_INGS_ERROR";

export const PURCHASE_INIT = "PURCHASE_INIT";
export const PURCHASE_LOADING = "PURCHASE_LOADING";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_ERROR = "PURCHASE_ERROR";

export const FETCH_ORDERS_INIT = "PURCHASE_ORDERS_INIT";
export const FETCH_ORDERS_SUCCESS = "PURCHASE_ORDERS_SUCCESS";
export const FETCH_ORDERS_ERROR = "PURCHASE_ORDERS_ERROR";

export const AUTH_INIT = "AUTH_INIT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";


